### ISSUE TITLE
missing increment of counter

### ISSUE THREAD

**Issue by mvaudel** [sdgroeve/ms2pip_c#2]
Hi guys,

Can it be than an `fnum++` is missing in the feature vector creation at the link below?
https://github.com/mvaudel/ms2pip_c/blob/master/ms2pipfeatures_c.c#L1248
Seems like the N-term pI is overwritten?

Best regards,

Marc

**Comment by mvaudel** [comment]
If yes, same at copy-pasted code:
https://github.com/mvaudel/ms2pip_c/blob/master/ms2pipfeatures_c.c#L1280
https://github.com/mvaudel/ms2pip_c/blob/master/ms2pipfeatures_c.c#L1312
https://github.com/mvaudel/ms2pip_c/blob/master/ms2pipfeatures_c.c#L1344

But one additional is introduced later:
https://github.com/mvaudel/ms2pip_c/blob/master/ms2pipfeatures_c.c#L1420

**Comment by sdgroeve** [comment]
You mean this?:
		v[fnum] = 0;
		if (peptide[pos] == 11) {
			v[fnum] = 1;
		}
		fnum++;
Because that is correct....the feature is 1 only if "peptide" at position "pos" equals 11, otherwise it is zero...

**Comment by mvaudel** [comment]
yes sorry I was doing too many things at a time - do you have some documentation on the different features that you use?

**Comment by sdgroeve** [comment]
nope...feature optimization is ongoing right now...
