### ISSUE TITLE
Local and online output prediction column not the same

### ISSUE THREAD

**Issue by Komegaga** [sdgroeve/ms2pip_c#22]
Hi,
I tried the same peptide file in local and online method. I got different result in prediction column.
The online prediction result could sum to 1 for every peptide. But the local result had the minus symbol.
Did they have different meaning?

**Comment by RalfG** [comment]
Hi @Komegaga,
MS²PIP normalizes the spectra by first dividing the peak intensities by the sum of all peaks in the spectrum and then taking the binary logarithm of every peak + 0.001:
```
peaks = peaks / np.sum(peaks)
peaks = np.array(np.log2(peaks + 0.001))
```
By default, MS²PIP outputs the results in the same logarithmic space, as these are the values the XGBoost model predicts. To be more user-friendly, the server version of MS²PIP 'unlogs' the values back to normal values, which are then also normalized to their sum.

There is a function in the local version of MS²PIP to write the predictions to an MGF file. It can be turned on by setting `MGF` to `True` on line [766](https://github.com/sdgroeve/ms2pip_c/blob/8f08bfc64f63cd4606eedcc115027a6c740b6d26/ms2pipC.py#L766). The resulting MGF will also have the 'unlogged' and normalized peak intensities.

**Comment by Komegaga** [comment]
Hi,
Thanks for these information.
Helps a lot!
