### ISSUE TITLE
Prediction output charge

### ISSUE THREAD

**Issue by Komegaga** [sdgroeve/ms2pip_c#24]
Hi,
I am not sure what charge type is in the prediction output result.
Is the charge type same as original input peptide sequence?

**Comment by RalfG** [comment]
Hi Komegaga,

The returned precursor peptide charges are always as you defined in the input peprec file (of input mgf file, if given). The fragment ion charges are always +1, unless you are using the HCD models that also include +2 charged fragment ions. In this case both +1 and +2 charged fragment ion peak intensities are returned.

Kind regards,
Ralf

**Comment by Komegaga** [comment]
Hi RalfG,

Thanks for response! It's remind me to read the readme file again. I founded that I missed the paragraph about setting +1 and +2 charged.
Thank you again!

Best regards,
Komegaga
